import {useEffect,useMemo,useState} from 'react'
import {Activity,BarChart3,BookOpen,CalendarDays,Check,CheckCircle2,Circle,Clock3,Flame,LayoutDashboard,ListTodo,Moon,Plus,RotateCcw,Save,Search,Settings,Sparkles,StickyNote,Sun,Target,Timer,Trash2,TrendingUp,Wallet,X} from 'lucide-react'
import './App.css'

type Task={id:string;title:string;done:boolean;priority:'Low'|'Medium'|'High'}
type Habit={id:string;name:string;doneDates:string[]}
type Goal={id:string;title:string;progress:number;deadline:string}
type Tx={id:string;label:string;amount:number;type:'income'|'expense';category:string}
type Note={id:string;title:string;content:string}
type Journal={id:string;date:string;mood:string;text:string}
type EventItem={id:string;title:string;date:string;time:string}
type Store={name:string;tasks:Task[];habits:Habit[];goals:Goal[];transactions:Tx[];notes:Note[];journal:Journal[];events:EventItem[];checkins:string[]}
const API_URL=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'')
const TOKEN_KEY='lifeos_access_token'
const PROFILE_KEY='lifeos_local_profile_v1'
// LifeOS is local-first: no password, Google login, or server account is required.
const isCloud=false
async function api<T>(path:string,options:RequestInit={}) {
  if(!API_URL) throw new Error('Cloud sync is not configured yet.')
  const token=localStorage.getItem(TOKEN_KEY)
  const res=await fetch(API_URL+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}),...(options.headers||{})}})
  let body:any=null
  try{body=await res.json()}catch{}
  if(!res.ok) throw new Error(body?.detail||body?.message||`Request failed (${res.status})`)
  return body as T
}

const K='lifeos_store_final'
const day=()=>{const d=new Date();return d.toISOString().slice(0,10)}
const id=()=>crypto.randomUUID()
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN')
const emptyStore=(name=''):Store=>({name,tasks:[],habits:[],goals:[],transactions:[],notes:[],journal:[],events:[],checkins:[]})
const valid=(v:unknown):v is Store=>!!v&&typeof v==='object'&&Array.isArray((v as Store).tasks)&&Array.isArray((v as Store).habits)
const load=()=>{try{const v=JSON.parse(localStorage.getItem(K)||'null');if(!valid(v))return emptyStore();if(v.name==='Gowtham'&&v.tasks?.some((t:Task)=>t.id==='1'&&t.title==='Plan today before starting'))return emptyStore();return v}catch{return emptyStore()}}
type LocalProfile={fullName:string;birthday?:string;createdAt:string}
const loadProfile=():LocalProfile|null=>{try{const p=JSON.parse(localStorage.getItem(PROFILE_KEY)||'null');return p&&typeof p.fullName==='string'&&p.fullName.trim()?p:null}catch{return null}}
const streak=(dates:string[])=>{const s=new Set(dates);let n=0;const d=new Date();while(s.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}

export default function App(){
 const [s,setS]=useState<Store>(load),[localProfile,setLocalProfile]=useState<LocalProfile|null>(loadProfile),[page,setPage]=useState('Overview'),[dark,setDark]=useState(localStorage.getItem('lifeos_theme')!=='light'),[toast,setToast]=useState(''),[query,setQuery]=useState(''),[menu,setMenu]=useState(false),[modal,setModal]=useState(false)
 const [profileOpen,setProfileOpen]=useState(false),[authReady,setAuthReady]=useState(true),[cloudUser,setCloudUser]=useState<{id:string;full_name:string;email:string}|null>(null),[,setSyncing]=useState(false),[,setAuthError]=useState('')
 useEffect(()=>localStorage.setItem('lifeos_theme',dark?'dark':'light'),[dark])
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(t)}},[toast])
 useEffect(()=>{
   if(!isCloud){setAuthReady(true);return}
   const token=localStorage.getItem(TOKEN_KEY)
   if(!token){setAuthReady(true);return}
   ;(async()=>{
     try{
       const me=await api<{id:string;full_name:string;email:string}>('/api/v1/auth/me')
       setCloudUser(me)
       const remote=await api<{data:Partial<Store>}>('/api/v1/state')
       if(remote.data && valid(remote.data)){setS(remote.data as Store)}
     }catch(e){localStorage.removeItem(TOKEN_KEY);setCloudUser(null);setAuthError(e instanceof Error?e.message:'Session expired')}
     finally{setAuthReady(true)}
   })()
 },[])
 useEffect(()=>{
   if(!isCloud||!cloudUser||!authReady)return
   const t=setTimeout(async()=>{try{setSyncing(true);await api('/api/v1/state',{method:'PUT',body:JSON.stringify({data:s})})}catch(e){setToast(e instanceof Error?e.message:'Sync failed')}finally{setSyncing(false)}},700)
   return()=>clearTimeout(t)
 },[s,cloudUser,authReady])
 useEffect(()=>{if(!localProfile)return;localStorage.setItem(K,JSON.stringify(s))},[s,localProfile])
 const update=(fn:(x:Store)=>Store)=>setS(x=>fn({...x}));const flash=(x:string)=>setToast(x)
 if(!localProfile)return <LocalProfileSetup onCreate={(profile)=>{localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));setLocalProfile(profile);setS(emptyStore(profile.fullName));localStorage.setItem(K,JSON.stringify(emptyStore(profile.fullName)))}} />

 const income=useMemo(()=>s.transactions.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0),[s]),expenses=useMemo(()=>s.transactions.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0),[s])
 const taskRate=Math.round(s.tasks.filter(x=>x.done).length/Math.max(1,s.tasks.length)*100),habitRate=Math.round(s.habits.filter(x=>x.doneDates.includes(day())).length/Math.max(1,s.habits.length)*100),goalRate=Math.round(s.goals.reduce((a,x)=>a+x.progress,0)/Math.max(1,s.goals.length)),score=Math.round(taskRate*.4+habitRate*.35+goalRate*.25)
 const nav=[['Overview',LayoutDashboard],['Tasks',ListTodo],['Habits',Flame],['Goals',Target],['Finance',Wallet],['Notes',StickyNote],['Journal',BookOpen],['Focus',Timer],['Calendar',CalendarDays]] as const
 const toggleTask=(i:string)=>update(x=>({...x,tasks:x.tasks.map(t=>t.id===i?{...t,done:!t.done}:t)}))
 const toggleHabit=(i:string)=>update(x=>({...x,habits:x.habits.map(h=>h.id===i?{...h,doneDates:h.doneDates.includes(day())?h.doneDates.filter(d=>d!==day()):[...h.doneDates,day()]}:h)}))
 return <div className={dark?'app dark':'app'}>
  <aside className={menu?'sidebar open':'sidebar'}><div className="brand"><span className="brandIcon"><Activity/></span><div><b>LifeOS</b><small>PERSONAL OS</small></div><button className="mobileClose" onClick={()=>setMenu(false)}><X/></button></div><nav>{nav.map(([n,I])=><button key={n} className={page===n?'nav active':'nav'} onClick={()=>{setPage(n);setMenu(false)}}><I/>{n}</button>)}</nav><div className="sidebarBottom"><button className="nav" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}{dark?'Light mode':'Dark mode'}</button><button className="nav" onClick={()=>setProfileOpen(true)}><Settings/>Account & Settings</button><div className="profile" onClick={()=>setProfileOpen(true)} role="button" tabIndex={0}><div className="avatar">{s.name[0]?.toUpperCase()||'L'}</div><div><b>{s.name||'Your profile'}</b><small>Saved on this device</small></div></div></div></aside>
  {menu&&<div className="mobileShade" onClick={()=>setMenu(false)}/>}<main className="main"><header className="topbar"><button className="mobileMenu iconBtn" onClick={()=>setMenu(true)}><ListTodo/></button><div><span className="eyebrow">{new Date().toDateString().toUpperCase()}</span><h1>{page==='Overview'?'Good evening, '+s.name+' 👋':page}</h1><p>Make today count. Small actions compound.</p></div><div className="topActions"><div className="searchBox"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search…"/></div><button className="iconBtn" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button className="primary" onClick={()=>setModal(true)}><Plus/>New task</button></div></header>
  {page==='Overview'&&<Overview s={s} score={score} taskRate={taskRate} habitRate={habitRate} income={income} expenses={expenses} toggleTask={toggleTask} toggleHabit={toggleHabit} setPage={setPage}/>}
  {page==='Tasks'&&<Tasks s={s} update={update} toggle={toggleTask}/>}
  {page==='Habits'&&<Habits s={s} update={update} toggle={toggleHabit}/>}
  {page==='Goals'&&<Goals s={s} update={update}/>}
  {page==='Finance'&&<Finance s={s} update={update} income={income} expenses={expenses}/>}
  {page==='Notes'&&<Notes s={s} update={update}/>}
  {page==='Journal'&&<Journal s={s} update={update}/>}
  {page==='Focus'&&<Focus s={s} update={update} flash={flash}/>}
  {page==='Calendar'&&<Calendar s={s} update={update}/>}
  {query&&<SearchResults q={query} s={s} setPage={setPage}/>}<footer><b>LifeOS</b> · Private to this browser/device · Your data is saved locally.</footer></main>
  {modal&&<QuickModal onClose={()=>setModal(false)} update={update} flash={flash}/>}
  {profileOpen&&<ProfileModal profile={localProfile} onClose={()=>setProfileOpen(false)} onLogout={()=>{localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(K);localStorage.removeItem(PROFILE_KEY);setCloudUser(null);setLocalProfile(null);setProfileOpen(false);setS(emptyStore())}}/>}{toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}
 </div>
}

function LocalProfileSetup(p:{onCreate:(profile:LocalProfile)=>void}){
 const [fullName,setFullName]=useState(''),[birthday,setBirthday]=useState(''),[error,setError]=useState('')
 const submit=()=>{const name=fullName.trim().replace(/\s+/g,' ');if(name.length<2){setError('Please enter your name (at least 2 characters).');return}p.onCreate({fullName:name,...(birthday?{birthday}:{}),createdAt:new Date().toISOString()})}
 return <div className="authShell"><div className="authCard localSetup">
  <div className="authBrand"><span className="brandIcon"><Activity/></span><span><b>LifeOS</b><small>YOUR PERSONAL SPACE</small></span></div>
  <span className="eyebrow">WELCOME — LET'S SET UP YOUR SPACE</span>
  <h1>Your life, your space.</h1>
  <p className="authLead">What should we call you? We'll personalize LifeOS for you. No account, password, Google sign-in, or email required.</p>
  <label className="setupLabel" htmlFor="lifeos-full-name">Your name</label>
  <input id="lifeos-full-name" autoFocus value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="e.g. Suresh Kumar" autoComplete="name" maxLength={80} onKeyDown={e=>e.key==='Enter'&&submit()}/>
  <label className="setupLabel" htmlFor="lifeos-birthday">Birthday <span>(optional)</span></label>
  <input id="lifeos-birthday" type="date" value={birthday} onChange={e=>setBirthday(e.target.value)}/>
  {error&&<div className="authError">{error}</div>}
  <button className="primary wide setupSubmit" onClick={submit}>Create my personal space <span aria-hidden="true">→</span></button>
  <small className="authPrivacy">Your profile and entries stay in this browser on this device. Don't enter sensitive information. Clearing browser data can erase your LifeOS.</small>
 </div></div>
}

function ProfileModal(p:{profile:LocalProfile|null;onClose:()=>void;onLogout:()=>void}){return <div className="modalBack" onClick={p.onClose}><div className="modal profileModal" onClick={e=>e.stopPropagation()}><div className="modalHead"><div><span className="eyebrow">YOUR PROFILE</span><h2>Personal space</h2></div><button className="iconBtn" onClick={p.onClose} aria-label="Close profile"><X/></button></div><div className="profileHero"><div className="profileAvatar">{p.profile?.fullName?.[0]?.toUpperCase()||'L'}</div><div><span className="eyebrow">LIFEOS USER</span><h2>{p.profile?.fullName||'Local profile'}</h2><p>This profile belongs to this device's browser.</p></div></div><div className="profileRows"><div><span>Profile</span><b>Device-only</b></div><div><span>Sync</span><b>Not enabled</b></div><div><span>Data storage</span><b>Saved in this browser</b></div>{p.profile?.birthday&&<div><span>Birthday</span><b>{p.profile.birthday}</b></div>}</div><p className="settingsNote">If you use a different phone or browser, it starts with a separate profile. LifeOS does not upload this information to a server.</p><button className="danger wide" onClick={()=>{if(window.confirm('Log out and erase this device’s LifeOS profile and all saved entries? This cannot be undone.'))p.onLogout()}}>Log out and erase device data</button><button className="secondary wide" onClick={p.onClose}>Cancel</button></div></div>}

function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="panel"><div className="panelHead"><div><span className="panelIcon">{icon}</span><h3>{title}</h3></div></div>{children}</section>}
function Overview(p:{s:Store;score:number;taskRate:number;habitRate:number;income:number;expenses:number;toggleTask:(i:string)=>void;toggleHabit:(i:string)=>void;setPage:(x:string)=>void}){return <div className="content"><section className="hero"><div className="heroMain"><div><span className="eyebrow">TODAY'S MOMENTUM</span><h2>Build the life you want,<br/><span>one day at a time.</span></h2><p>Your personal dashboard for focus, habits, goals and money.</p></div><div className="scoreRing"><strong>{p.score}</strong><span>/100</span><small>Momentum</small></div></div><div className="heroStats"><div><Flame/><b>{streak(p.s.checkins)}</b><span>day streak</span></div><div><CheckCircle2/><b>{p.taskRate}%</b><span>tasks complete</span></div><div><Target/><b>{p.habitRate}%</b><span>habits today</span></div><button onClick={()=>p.setPage('Journal')}><Sparkles/> Check in</button></div></section><section className="grid3"><Panel title="Today's tasks" icon={<ListTodo/>}><div className="list">{p.s.tasks.slice(0,4).map(t=><button className="row" key={t.id} onClick={()=>p.toggleTask(t.id)}><span className={t.done?'check done':'check'}>{t.done&&<Check/>}</span><span className={t.done?'strike':''}>{t.title}</span><em className={'p '+t.priority.toLowerCase()}>{t.priority}</em></button>)}</div></Panel><Panel title="Habit pulse" icon={<Flame/>}><div className="list">{p.s.habits.map(h=><button className="row" key={h.id} onClick={()=>p.toggleHabit(h.id)}><span className={h.doneDates.includes(day())?'check done':'check'}>{h.doneDates.includes(day())&&<Check/>}</span><span>{h.name}</span><em className="streak"><Flame size={13}/>{streak(h.doneDates)}</em></button>)}</div></Panel><Panel title="Money snapshot" icon={<Wallet/>}><div className="moneyHero"><small>NET SAVINGS</small><strong>{money(p.income-p.expenses)}</strong><span><TrendingUp size={14}/> this month</span></div><div className="moneyLine"><span>Income</span><b>{money(p.income)}</b></div><div className="moneyLine"><span>Expenses</span><b>{money(p.expenses)}</b></div></Panel></section><section className="grid2"><Panel title="Goals in motion" icon={<Target/>}><div className="goalList">{p.s.goals.map(g=><div className="goal" key={g.id}><div className="goalTop"><span>{g.title}</span><b>{g.progress}%</b></div><div className="bar"><i style={{width:g.progress+'%'}}/></div><small>{g.deadline}</small></div>)}</div></Panel><Panel title="LifeOS at a glance" icon={<BarChart3/>}><div className="metricGrid"><div><span>Goals average</span><b>{Math.round(p.s.goals.reduce((a,g)=>a+g.progress,0)/Math.max(1,p.s.goals.length))}%</b></div><div><span>Focus sessions</span><b>{p.s.journal.length}</b></div><div><span>Notes</span><b>{p.s.notes.length}</b></div><div><span>Events</span><b>{p.s.events.length}</b></div></div></Panel></section></div>}

function Tasks(p:{s:Store;update:(f:(s:Store)=>Store)=>void;toggle:(i:string)=>void}){const [v,setV]=useState('');return <div className="content page"><Panel title="Task inbox" icon={<ListTodo/>}><div className="quick"><input value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&v){p.update(s=>({...s,tasks:[...s.tasks,{id:id(),title:v,done:false,priority:'Medium'}]}));setV('')}}} placeholder="Add a task…"/><button className="primary" onClick={()=>{if(v){p.update(s=>({...s,tasks:[...s.tasks,{id:id(),title:v,done:false,priority:'Medium'}]}));setV('')}}}><Plus/>Add</button></div>{p.s.tasks.map(t=><div className="taskItem" key={t.id}><button className={t.done?'check done':'check'} onClick={()=>p.toggle(t.id)}>{t.done&&<Check/>}</button><div className="grow"><b className={t.done?'strike':''}>{t.title}</b><small>{t.priority} priority</small></div><button className="delete" onClick={()=>p.update(s=>({...s,tasks:s.tasks.filter(x=>x.id!==t.id)}))}><Trash2/></button></div>)}</Panel></div>}
function Habits(p:{s:Store;update:(f:(s:Store)=>Store)=>void;toggle:(i:string)=>void}){const [v,setV]=useState('');return <div className="content page"><Panel title="Habit tracker" icon={<Flame/>}><div className="quick"><input value={v} onChange={e=>setV(e.target.value)} placeholder="Create a habit…"/><button className="primary" onClick={()=>{if(v){p.update(s=>({...s,habits:[...s.habits,{id:id(),name:v,doneDates:[]}]}));setV('')}}}><Plus/>Add</button></div><div className="habitCards">{p.s.habits.map(h=><div className="habitCard" key={h.id}><button className={h.doneDates.includes(day())?'habitCheck active':'habitCheck'} onClick={()=>p.toggle(h.id)}>{h.doneDates.includes(day())?<Check/>:<Circle/>}</button><div className="grow"><b>{h.name}</b><small>{h.doneDates.includes(day())?'Completed today':'Tap to complete today'}</small></div><strong><Flame size={15}/>{streak(h.doneDates)}<small>day streak</small></strong><button className="delete" onClick={()=>p.update(s=>({...s,habits:s.habits.filter(x=>x.id!==h.id)}))}><Trash2/></button></div>)}</div></Panel></div>}
function Goals(p:{s:Store;update:(f:(s:Store)=>Store)=>void}){return <div className="content page"><Panel title="Goals" icon={<Target/>}><div className="goalCards">{p.s.goals.map(g=><div className="goalCard" key={g.id}><div className="goalTop"><b>{g.title}</b><button className="delete" onClick={()=>p.update(s=>({...s,goals:s.goals.filter(x=>x.id!==g.id)}))}><Trash2/></button></div><div className="goalBig"><strong>{g.progress}%</strong><span>complete</span></div><input className="range" type="range" min="0" max="100" value={g.progress} onChange={e=>p.update(s=>({...s,goals:s.goals.map(x=>x.id===g.id?{...x,progress:+e.target.value}:x)}))}/><small>Target · {g.deadline}</small></div>)}</div></Panel></div>}
function Finance(p:{s:Store;update:(f:(s:Store)=>Store)=>void;income:number;expenses:number}){const [label,setLabel]=useState(''),[amt,setAmt]=useState(''),[type,setType]=useState<'income'|'expense'>('expense');return <div className="content page"><section className="financeCards"><div><small>INCOME</small><strong>{money(p.income)}</strong></div><div><small>EXPENSES</small><strong>{money(p.expenses)}</strong></div><div><small>SAVINGS</small><strong>{money(p.income-p.expenses)}</strong></div></section><Panel title="Add transaction" icon={<Wallet/>}><div className="financeForm"><input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Description"/><input type="number" value={amt} onChange={e=>setAmt(e.target.value)} placeholder="Amount"/><select value={type} onChange={e=>setType(e.target.value as 'income'|'expense')}><option value="expense">Expense</option><option value="income">Income</option></select><button className="primary" onClick={()=>{if(label&&+amt){p.update(s=>({...s,transactions:[...s.transactions,{id:id(),label,amount:+amt,type,category:'General'}]}));setLabel('');setAmt('')}}}><Plus/>Add</button></div></Panel><Panel title="Transactions" icon={<Wallet/>}>{p.s.transactions.slice().reverse().map(x=><div className="taskItem" key={x.id}><span className={x.type==='income'?'txIcon income':'txIcon expense'}>{x.type==='income'?'+':'−'}</span><div className="grow"><b>{x.label}</b><small>{x.category}</small></div><strong className={x.type}>{x.type==='income'?'+':'−'} {money(x.amount)}</strong><button className="delete" onClick={()=>p.update(s=>({...s,transactions:s.transactions.filter(t=>t.id!==x.id)}))}><Trash2/></button></div>)}</Panel></div>}
function Notes(p:{s:Store;update:(f:(s:Store)=>Store)=>void}){const [t,setT]=useState(''),[c,setC]=useState('');return <div className="content page"><Panel title="Notes" icon={<StickyNote/>}><div className="noteEditor"><input value={t} onChange={e=>setT(e.target.value)} placeholder="Title"/><textarea value={c} onChange={e=>setC(e.target.value)} placeholder="Write anything…"/><button className="primary" onClick={()=>{if(t||c){p.update(s=>({...s,notes:[...s.notes,{id:id(),title:t||'Untitled',content:c}]}));setT('');setC('')}}}><Save/>Save note</button></div><div className="noteGrid">{p.s.notes.map(n=><article className="noteCard" key={n.id}><button className="delete" onClick={()=>p.update(s=>({...s,notes:s.notes.filter(x=>x.id!==n.id)}))}><Trash2/></button><h3>{n.title}</h3><p>{n.content}</p></article>)}</div></Panel></div>}
function Journal(p:{s:Store;update:(f:(s:Store)=>Store)=>void}){const [v,setV]=useState(''),[m,setM]=useState('Focused');return <div className="content page"><Panel title="Daily journal" icon={<BookOpen/>}><div className="moods">{['Great','Focused','Calm','Okay','Tired'].map(x=><button className={m===x?'mood active':'mood'} key={x} onClick={()=>setM(x)}>{x}</button>)}</div><textarea className="journalText" value={v} onChange={e=>setV(e.target.value)} placeholder="How did today go? What did you learn?"/><button className="primary" onClick={()=>{if(v){p.update(s=>({...s,journal:[...s.journal,{id:id(),date:day(),mood:m,text:v}]}));setV('')}}}><Save/>Save reflection</button>{p.s.journal.slice().reverse().map(j=><div className="journalItem" key={j.id}><b>{j.date} · {j.mood}</b><p>{j.text}</p><button className="delete" onClick={()=>p.update(s=>({...s,journal:s.journal.filter(x=>x.id!==j.id)}))}><Trash2/></button></div>)}</Panel></div>}
function Focus(p:{s:Store;update:(f:(s:Store)=>Store)=>void;flash:(x:string)=>void}){const [sec,setSec]=useState(1500),[run,setRun]=useState(false);useEffect(()=>{if(!run)return;const t=setInterval(()=>setSec(x=>{if(x<=1){clearInterval(t);setRun(false);p.update(s=>({...s,checkins:s.checkins.includes(day())?s.checkins:[...s.checkins,day()]}));p.flash('Focus session complete!');return 1500}return x-1}),1000);return()=>clearInterval(t)},[run]);return <div className="content page"><div className="focusLayout"><Panel title="Focus timer" icon={<Timer/>}><div className="timer"><span>{String(Math.floor(sec/60)).padStart(2,'0')}:{String(sec%60).padStart(2,'0')}</span><div><button className="primary" onClick={()=>setRun(!run)}>{run?'Pause':'Start focus'}</button><button className="secondary" onClick={()=>{setRun(false);setSec(1500)}}><RotateCcw/>Reset</button></div></div></Panel><Panel title="Focus guide" icon={<Clock3/>}><div className="metricGrid"><div><span>Method</span><b>25 / 5</b></div><div><span>Today</span><b>{p.s.checkins.length}</b></div></div><p className="muted">Put one task in front of you, remove distractions, and finish the block.</p></Panel></div></div>}
function Calendar(p:{s:Store;update:(f:(s:Store)=>Store)=>void}){const [t,setT]=useState(''),[d,setD]=useState(day()),[tm,setTm]=useState('20:00');return <div className="content page"><Panel title="Calendar" icon={<CalendarDays/>}><div className="calendarForm"><input value={t} onChange={e=>setT(e.target.value)} placeholder="Event title"/><input type="date" value={d} onChange={e=>setD(e.target.value)}/><input type="time" value={tm} onChange={e=>setTm(e.target.value)}/><button className="primary" onClick={()=>{if(t){p.update(s=>({...s,events:[...s.events,{id:id(),title:t,date:d,time:tm}]}));setT('')}}}><Plus/>Add</button></div>{p.s.events.map(e=><div className="eventItem" key={e.id}><div className="eventDate"><b>{e.date.slice(8)}</b><small>{e.date.slice(5,7)}</small></div><div className="grow"><b>{e.title}</b><small>{e.time}</small></div><button className="delete" onClick={()=>p.update(s=>({...s,events:s.events.filter(x=>x.id!==e.id)}))}><Trash2/></button></div>)}</Panel></div>}
function SearchResults(p:{q:string;s:Store;setPage:(x:string)=>void}){const q=p.q.toLowerCase();const r=[...p.s.tasks.filter(x=>x.title.toLowerCase().includes(q)).map(x=>['Tasks',x.title]),...p.s.habits.filter(x=>x.name.toLowerCase().includes(q)).map(x=>['Habits',x.name]),...p.s.goals.filter(x=>x.title.toLowerCase().includes(q)).map(x=>['Goals',x.title]),...p.s.notes.filter(x=>x.title.toLowerCase().includes(q)).map(x=>['Notes',x.title])];if(!r.length)return null;return <div className="searchResults">{r.slice(0,7).map((x,i)=><button key={i} onClick={()=>p.setPage(x[0])}><span>{x[0]}</span><b>{x[1]}</b></button>)}</div>}
function QuickModal(p:{onClose:()=>void;update:(f:(s:Store)=>Store)=>void;flash:(x:string)=>void}){const [v,setV]=useState('');return <div className="modalBack" onClick={p.onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modalHead"><div><span className="eyebrow">QUICK CAPTURE</span><h2>Add a task</h2></div><button className="iconBtn" onClick={p.onClose}><X/></button></div><input autoFocus value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&v){p.update(s=>({...s,tasks:[...s.tasks,{id:id(),title:v,done:false,priority:'Medium'}]}));p.flash('Task added');p.onClose()}}} placeholder="What needs to get done?"/><button className="primary wide" onClick={()=>{if(v){p.update(s=>({...s,tasks:[...s.tasks,{id:id(),title:v,done:false,priority:'Medium'}]}));p.flash('Task added');p.onClose()}}}><Plus/>Add task</button></div></div>}
