import { useEffect, useMemo, useRef, useState } from 'react'
import { Activity, BarChart3, Check, CheckCircle2, Circle, Download, Flame, LayoutDashboard, ListTodo, Moon, Plus, RotateCcw, Settings, ShieldCheck, Sparkles, Sun, Target, Trash2, TrendingUp, Upload, Wallet, X } from 'lucide-react'
import './App.css'

type Task={id:string;title:string;done:boolean;priority:'Low'|'Medium'|'High'}
type Habit={id:string;name:string;streak:number;doneToday:boolean}
type Goal={id:string;title:string;progress:number;deadline:string}
type Tx={id:string;label:string;amount:number;type:'income'|'expense';category:string}
type Store={tasks:Task[];habits:Habit[];goals:Goal[];transactions:Tx[];checkins:string[];name:string}
const STORAGE_KEY='lifeos_store_v2'
const todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const longDate=()=>new Intl.DateTimeFormat('en-IN',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(new Date())
const checkinStreak=(dates:string[])=>{const set=new Set(dates);let count=0;const d=new Date();d.setHours(12,0,0,0);while(set.has(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`)){count++;d.setDate(d.getDate()-1)}return count}
const validStore=(value:unknown):value is Store=>{if(!value||typeof value!=='object')return false;const v=value as Partial<Store>;return Array.isArray(v.tasks)&&Array.isArray(v.habits)&&Array.isArray(v.goals)&&Array.isArray(v.transactions)&&Array.isArray(v.checkins)&&typeof v.name==='string'}
const seed:Store={name:'Gowtham',tasks:[{id:'t1',title:'Plan today before starting',done:true,priority:'High'},{id:'t2',title:'Build one useful feature',done:false,priority:'High'},{id:'t3',title:'Read and learn for 30 minutes',done:false,priority:'Medium'},{id:'t4',title:"Review tomorrow's priorities",done:false,priority:'Low'}],habits:[{id:'h1',name:'Morning routine',streak:7,doneToday:true},{id:'h2',name:'Read / learn',streak:12,doneToday:false},{id:'h3',name:'Exercise',streak:4,doneToday:false}],goals:[{id:'g1',title:'Build a strong public portfolio',progress:68,deadline:'Dec 2026'},{id:'g2',title:'Create 30 useful websites',progress:24,deadline:'Jun 2027'},{id:'g3',title:'Improve coding skills',progress:51,deadline:'Ongoing'}],transactions:[{id:'x1',label:'Salary',amount:18000,type:'income',category:'Income'},{id:'x2',label:'Subscriptions',amount:1500,type:'expense',category:'Lifestyle'},{id:'x3',label:'Wi-Fi',amount:500,type:'expense',category:'Bills'}],checkins:[todayKey()]}
function loadStore():Store{try{const raw=localStorage.getItem(STORAGE_KEY);const parsed=raw?JSON.parse(raw):null;return validStore(parsed)?parsed:seed}catch{return seed}}
export default function App(){
 const [store,setStore]=useState<Store>(loadStore),[active,setActive]=useState('Overview'),[dark,setDark]=useState(true),[showAdd,setShowAdd]=useState(false),[showSettings,setShowSettings]=useState(false),[newTask,setNewTask]=useState(''),[newHabit,setNewHabit]=useState(''),[toast,setToast]=useState('')
 const importRef=useRef<HTMLInputElement>(null)
 useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(store))}catch{}},[store]);useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(t)}},[toast])
 const income=useMemo(()=>store.transactions.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0),[store]),expenses=useMemo(()=>store.transactions.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0),[store]),savings=income-expenses,completed=store.tasks.filter(x=>x.done).length,taskRate=Math.round(completed/Math.max(store.tasks.length,1)*100),habitRate=Math.round(store.habits.filter(x=>x.doneToday).length/Math.max(store.habits.length,1)*100),score=Math.min(100,Math.round(taskRate*.45+habitRate*.35+(store.goals.reduce((a,g)=>a+g.progress,0)/Math.max(store.goals.length,1))*.2)),streak=checkinStreak(store.checkins)
 const update=(fn:(s:Store)=>Store)=>setStore(s=>fn({...s})),flash=(m:string)=>setToast(m)
 const toggleTask=(id:string)=>update(s=>({...s,tasks:s.tasks.map(t=>t.id===id?{...t,done:!t.done}:t)}))
 const toggleHabit=(id:string)=>update(s=>({...s,habits:s.habits.map(h=>h.id===id?{...h,doneToday:!h.doneToday,streak:!h.doneToday?h.streak+1:Math.max(0,h.streak-1)}:h)}))
 const checkIn=()=>{const k=todayKey();if(!store.checkins.includes(k)){update(s=>({...s,checkins:[...s.checkins,k]}));flash('Daily check-in complete. Keep the streak alive!')}else flash('You already checked in today.')}
 const exportData=()=>{const blob=new Blob([JSON.stringify(store,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`lifeos-backup-${todayKey()}.json`;a.click();URL.revokeObjectURL(url);flash('Backup exported successfully')}
 const importData=(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result));if(!validStore(parsed))throw new Error('Invalid LifeOS backup');setStore(parsed);flash('Backup restored successfully')}catch{flash('That backup file is not valid LifeOS data')}finally{if(importRef.current)importRef.current.value=''}};reader.readAsText(file)}
 const resetData=()=>{if(window.confirm('Reset LifeOS to the polished demo data? Your current browser data will be replaced.')){setStore(seed);flash('Demo data restored')}}
 const addTask=()=>{if(!newTask.trim())return;update(s=>({...s,tasks:[...s.tasks,{id:crypto.randomUUID(),title:newTask.trim(),done:false,priority:'Medium'}]}));setNewTask('');setShowAdd(false);flash('Task added')}
 const addHabit=()=>{if(!newHabit.trim())return;update(s=>({...s,habits:[...s.habits,{id:crypto.randomUUID(),name:newHabit.trim(),streak:0,doneToday:false}]}));setNewHabit('');flash('Habit added')}
 const deleteTask=(id:string)=>update(s=>({...s,tasks:s.tasks.filter(t=>t.id!==id)}))
 const nav=['Overview','Tasks','Habits','Goals','Finance']
 return <div className={dark?'app dark':'app'}>
  <aside className="sidebar"><div className="brand"><span className="brandIcon"><Activity size={20}/></span><div><b>LifeOS</b><small>PERSONAL OS</small></div></div><nav>{nav.map((n,i)=><button key={n} className={active===n?'nav active':'nav'} onClick={()=>setActive(n)}>{i===0?<LayoutDashboard/>:i===1?<ListTodo/>:i===2?<Flame/>:i===3?<Target/>:<Wallet/>}{n}</button>)}</nav><div className="sidebarBottom"><button className="nav" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}{dark?'Light mode':'Dark mode'}</button><button className="nav" onClick={()=>setShowSettings(true)}><Settings/>Settings</button><div className="profile"><div className="avatar">G</div><div><b>{store.name}</b><small>Building in public</small></div></div></div></aside>
  <main className="main"><header className="topbar"><div><span className="eyebrow">{longDate().toUpperCase()}</span><h1>{active==='Overview'?'Good evening, '+store.name+' 👋':active}</h1><p>Make today count. Small actions compound.</p></div><div className="topActions"><button className="iconBtn" aria-label="Toggle theme" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button className="primary" onClick={()=>setShowAdd(true)}><Plus/> New task</button></div></header>
   {active==='Overview'&&<Overview store={store} score={score} streak={streak} taskRate={taskRate} habitRate={habitRate} income={income} expenses={expenses} savings={savings} toggleTask={toggleTask} toggleHabit={toggleHabit} checkIn={checkIn}/>}
   {active==='Tasks'&&<Tasks store={store} toggleTask={toggleTask} deleteTask={deleteTask} newTask={newTask} setNewTask={setNewTask} addTask={addTask}/>}
   {active==='Habits'&&<Habits store={store} toggleHabit={toggleHabit} newHabit={newHabit} setNewHabit={setNewHabit} addHabit={addHabit}/>}
   {active==='Goals'&&<Goals store={store}/>}
   {active==='Finance'&&<Finance store={store} income={income} expenses={expenses} savings={savings}/>}
   <footer><span>LifeOS</span> · Your life, organized. <span className="footerRight">Local-first demo · Data stays in this browser</span></footer></main>
   {showSettings&&<div className="modalBack" onClick={()=>setShowSettings(false)}><div className="modal settingsModal" onClick={e=>e.stopPropagation()}><div className="modalHead"><div><span className="eyebrow">LIFEOS CONTROL CENTER</span><h2>Settings</h2></div><button className="iconBtn" aria-label="Close settings" onClick={()=>setShowSettings(false)}><X/></button></div><div className="settingsCard"><ShieldCheck size={19}/><div><b>Private by design</b><small>Your tasks, habits, goals and finance data are stored in this browser. Nothing is sent to the LifeOS demo server.</small></div></div><div className="settingsActions"><button className="settingAction" onClick={exportData}><Download/><span><b>Export backup</b><small>Save your LifeOS data as JSON</small></span></button><button className="settingAction" onClick={()=>importRef.current?.click()}><Upload/><span><b>Import backup</b><small>Restore a previous JSON backup</small></span></button><button className="settingAction danger" onClick={resetData}><RotateCcw/><span><b>Reset demo data</b><small>Restore the original sample dashboard</small></span></button></div><input ref={importRef} className="hiddenInput" type="file" accept="application/json,.json" onChange={importData}/><p className="settingsNote">Tip: export a backup before changing devices or clearing browser storage.</p></div></div>}
   {showAdd&&<div className="modalBack" onClick={()=>setShowAdd(false)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modalHead"><div><span className="eyebrow">QUICK CAPTURE</span><h2>Add a task</h2></div><button className="iconBtn" onClick={()=>setShowAdd(false)}><X/></button></div><input autoFocus value={newTask} onChange={e=>setNewTask(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')addTask()}} placeholder="What needs to get done?"/><button className="primary wide" onClick={addTask}>Add to today</button></div></div>}
   {toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}
 </div>
}
function Overview({store,score,streak,taskRate,habitRate,income,expenses,savings,toggleTask,toggleHabit,checkIn}:{store:Store;score:number;streak:number;taskRate:number;habitRate:number;income:number;expenses:number;savings:number;toggleTask:(id:string)=>void;toggleHabit:(id:string)=>void;checkIn:()=>void}){return <div className="content"><section className="hero"><div className="heroMain"><div><span className="eyebrow">TODAY'S MOMENTUM</span><h2>Build the life you want,<br/><span>one day at a time.</span></h2><p>Your personal dashboard for focus, habits, goals and money.</p></div><div className="scoreRing"><strong>{score}</strong><span>/100</span><small>Momentum</small></div></div><div className="heroStats"><div><Flame/><b>{streak}</b><span>day streak</span></div><div><CheckCircle2/><b>{taskRate}%</b><span>tasks complete</span></div><div><Target/><b>{habitRate}%</b><span>habits today</span></div><button onClick={checkIn}><Sparkles/> Check in today</button></div></section>
 <section className="grid3"><Panel title="Today's tasks" icon={<ListTodo/>}><div className="list">{store.tasks.slice(0,4).map(t=><button className="row" key={t.id} onClick={()=>toggleTask(t.id)}><span className={t.done?'check done':'check'}>{t.done&&<Check size={15}/>}</span><span className={t.done?'strike':''}>{t.title}</span><em className={'p '+t.priority.toLowerCase()}>{t.priority}</em></button>)}</div></Panel><Panel title="Habit pulse" icon={<Flame/>}><div className="list">{store.habits.map(h=><button className="row" key={h.id} onClick={()=>toggleHabit(h.id)}><span className={h.doneToday?'check done':'check'}>{h.doneToday&&<Check size={15}/>}</span><span>{h.name}</span><em className="streak"><Flame size={13}/>{h.streak}</em></button>)}</div></Panel><Panel title="Money snapshot" icon={<Wallet/>}><div className="moneyHero"><small>NET SAVINGS</small><strong>₹{savings.toLocaleString('en-IN')}</strong><span><TrendingUp size={14}/> this month</span></div><div className="moneyLine"><span>Income</span><b>₹{income.toLocaleString('en-IN')}</b></div><div className="moneyLine"><span>Expenses</span><b>₹{expenses.toLocaleString('en-IN')}</b></div></Panel></section>
 <section className="grid2"><Panel title="Goals in motion" icon={<Target/>}><div className="goalList">{store.goals.map(g=><div className="goal" key={g.id}><div className="goalTop"><span>{g.title}</span><b>{g.progress}%</b></div><div className="bar"><i style={{width:g.progress+'%'}}/></div><small>Target · {g.deadline}</small></div>)}</div></Panel><Panel title="Your progress" icon={<BarChart3/>}><div className="week">{['MON','TUE','WED','THU','FRI','SAT','SUN'].map(x=><span key={x}>{x}</span>)}</div><div className="bars">{[42,68,55,86,62,30,74].map((v,i)=><div className={i===3?'barCol today':'barCol'} key={i}><i style={{height:v+'%'}}/></div>)}</div><p className="insight"><Sparkles size={15}/> You're building consistency. Keep going.</p></Panel></section></div>}
function Panel({title,icon,children}:{title:string;icon?:React.ReactNode;children:React.ReactNode}){return <section className="panel"><div className="panelHead"><div><span className="panelIcon">{icon}</span><h3>{title}</h3></div></div>{children}</section>}
function Tasks({store,toggleTask,deleteTask,newTask,setNewTask,addTask}:{store:Store;toggleTask:(id:string)=>void;deleteTask:(id:string)=>void;newTask:string;setNewTask:(v:string)=>void;addTask:()=>void}){return <div className="content page"><Panel title="Task inbox" icon={<ListTodo/>}><div className="quick"><input value={newTask} onChange={e=>setNewTask(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')addTask()}} placeholder="Add something you want to accomplish…"/><button className="primary" onClick={addTask}><Plus/> Add</button></div><div className="taskFull">{store.tasks.map(t=><div className="taskItem" key={t.id}><button onClick={()=>toggleTask(t.id)} className={t.done?'check done':'check'}>{t.done&&<Check size={15}/>}</button><div><b className={t.done?'strike':''}>{t.title}</b><small>{t.priority} priority · Today</small></div><button className="delete" onClick={()=>deleteTask(t.id)}><Trash2 size={16}/></button></div>)}</div></Panel></div>}
function Habits({store,toggleHabit,newHabit,setNewHabit,addHabit}:{store:Store;toggleHabit:(id:string)=>void;newHabit:string;setNewHabit:(v:string)=>void;addHabit:()=>void}){return <div className="content page"><Panel title="Habit tracker" icon={<Flame/>}><div className="quick"><input value={newHabit} onChange={e=>setNewHabit(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')addHabit()}} placeholder="Create a habit…"/><button className="primary" onClick={addHabit}><Plus/> Add</button></div><div className="habitCards">{store.habits.map(h=><button className="habitCard" key={h.id} onClick={()=>toggleHabit(h.id)}><span className={h.doneToday?'habitCheck active':'habitCheck'}>{h.doneToday?<Check/>:<Circle/>}</span><div><b>{h.name}</b><small>{h.doneToday?'Completed today':'Tap to complete today'}</small></div><strong><Flame size={15}/>{h.streak}<small>day streak</small></strong></button>)}</div></Panel></div>}
function Goals({store}:{store:Store}){return <div className="content page"><div className="grid2">{store.goals.map(g=><Panel key={g.id} title={g.title} icon={<Target/>}><div className="goalBig"><strong>{g.progress}%</strong><span>complete</span></div><div className="bar big"><i style={{width:g.progress+'%'}}/></div><p className="muted">Target · {g.deadline}</p></Panel>)}</div></div>}
function Finance({store,income,expenses,savings}:{store:Store;income:number;expenses:number;savings:number}){return <div className="content page"><section className="financeCards"><div><small>INCOME</small><strong>₹{income.toLocaleString('en-IN')}</strong></div><div><small>EXPENSES</small><strong>₹{expenses.toLocaleString('en-IN')}</strong></div><div><small>SAVINGS</small><strong>₹{savings.toLocaleString('en-IN')}</strong></div></section><Panel title="Recent transactions" icon={<Wallet/>}><div className="taskFull">{store.transactions.map(x=><div className="taskItem" key={x.id}><span className="txIcon">{x.type==='income'?'+':'−'}</span><div><b>{x.label}</b><small>{x.category}</small></div><strong className={x.type==='income'?'income':'expense'}>{x.type==='income'?'+':'−'} ₹{x.amount.toLocaleString('en-IN')}</strong></div>)}</div></Panel></div>}
