import {useEffect,useMemo,useState} from 'react'
import {Activity,BarChart3,BookOpen,CalendarDays,Check,CheckCircle2,Circle,Clock3,Flame,LayoutDashboard,ListTodo,Moon,Plus,RotateCcw,Save,Search,Settings,Sparkles,StickyNote,Sun,Target,Timer,Trash2,TrendingUp,Wallet,X} from 'lucide-react'
import './App.css'

type Task={id:string;title:string;done:boolean;priority:'Low'|'Medium'|'High'}
type Habit={id:string;name:string;doneDates:string[]}
type Goal={id:string;title:string;progress:number;deadline:string}
type Tx={id:string;label:string;amount:number;type:'income'|'expense';category:string}
type Note={id:string;title:string;content:string}
type Journal={id:string;date:string;mood:string;text:string}
type EventItem={id:string;title:string;date:string;time:string}
type Store={name:string;tasks:Task[];habits:Habit[];goals:Goal[];transactions:Tx[];notes:Note[];journal:Journal[];events:EventItem[];checkins:string[]}
const API_URL=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'')
const TOKEN_KEY='lifeos_access_token'
const isCloud=Boolean(API_URL)
async function api<T>(path:string,options:RequestInit={}) {
  if(!API_URL) throw new Error('Cloud sync is not configured yet.')
  const token=localStorage.getItem(TOKEN_KEY)
  const res=await fetch(API_URL+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}),...(options.headers||{})}})
  let body:any=null
  try{body=await res.json()}catch{}
  if(!res.ok) throw new Error(body?.detail||body?.message||`Request failed (${res.status})`)
  return body as T
}

const K='lifeos_store_final'
const day=()=>{const d=new Date();return d.toISOString().slice(0,10)}
const id=()=>crypto.randomUUID()
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN')
const seed:Store={name:'Gowtham',tasks:[{id:'1',title:'Plan today before starting',done:true,priority:'High'},{id:'2',title:'Build one useful feature',done:false,priority:'High'},{id:'3',title:'Read and learn',done:false,priority:'Medium'}],habits:[{id:'1',name:'Morning routine',doneDates:[day()]},{id:'2',name:'Read / learn',doneDates:[]},{id:'3',name:'Exercise',doneDates:[]}],goals:[{id:'1',title:'Build a strong public portfolio',progress:68,deadline:'2026-12-31'},{id:'2',title:'Create 30 useful websites',progress:24,deadline:'2027-06-30'}],transactions:[{id:'1',label:'Salary',amount:18000,type:'income',category:'Income'},{id:'2',label:'Subscriptions',amount:1500,type:'expense',category:'Lifestyle'},{id:'3',label:'Wi-Fi',amount:500,type:'expense',category:'Bills'}],notes:[{id:'1',title:'LifeOS idea',content:'Keep building in public. Every shipped feature is a lesson.'}],journal:[{id:'1',date:day(),mood:'Focused',text:'Today I shipped another piece of LifeOS.'}],events:[{id:'1',title:'LifeOS build session',date:day(),time:'20:30'}],checkins:[day()]}
const valid=(v:unknown):v is Store=>!!v&&typeof v==='object'&&Array.isArray((v as Store).tasks)&&Array.isArray((v as Store).habits)
const load=()=>{try{const v=JSON.parse(localStorage.getItem(K)||'null');return valid(v)?v:seed}catch{return seed}}
const streak=(dates:string[])=>{const s=new Set(dates);let n=0;const d=new Date();while(s.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}

export default function App(){
 const [s,setS]=useState<Store>(load),[page,setPage]=useState('Overview'),[dark,setDark]=useState(localStorage.getItem('lifeos_theme')!=='light'),[toast,setToast]=useState(''),[query,setQuery]=useState(''),[menu,setMenu]=useState(false),[modal,setModal]=useState(false)
 const [profileOpen,setProfileOpen]=useState(false),[authReady,setAuthReady]=useState(!isCloud),[cloudUser,setCloudUser]=useState<{id:string;full_name:string;email:string}|null>(null),[syncing,setSyncing]=useState(false),[authError,setAuthError]=useState('')
 useEffect(()=>localStorage.setItem('lifeos_theme',dark?'dark':'light'),[dark])
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(t)}},[toast])
 useEffect(()=>{
   if(!isCloud){setAuthReady(true);return}
   const token=localStorage.getItem(TOKEN_KEY)
   if(!token){setAuthReady(true);return}
   ;(async()=>{
     try{
       const me=await api<{id:string;full_name:string;email:string}>('/api/v1/auth/me')
       setCloudUser(me)
       const remote=await api<{data:Partial<Store>}>('/api/v1/state')
       if(remote.data && valid(remote.data)){setS(remote.data as Store)}
     }catch(e){localStorage.removeItem(TOKEN_KEY);setCloudUser(null);setAuthError(e instanceof Error?e.message:'Session expired')}
     finally{setAuthReady(true)}
   })()
 },[])
 useEffect(()=>{
   if(!isCloud||!cloudUser||!authReady)return
   const t=setTimeout(async()=>{try{setSyncing(true);await api('/api/v1/state',{method:'PUT',body:JSON.stringify({data:s})})}catch(e){setToast(e instanceof Error?e.message:'Sync failed')}finally{setSyncing(false)}},700)
   return()=>clearTimeout(t)
 },[s,cloudUser,authReady])
 useEffect(()=>{if(!isCloud||!cloudUser)return;localStorage.setItem(K,JSON.stringify(s))},[s,cloudUser])
 const update=(fn:(x:Store)=>Store)=>setS(x=>fn({...x}));const flash=(x:string)=>setToast(x)
 if(!authReady)return <div className="authShell"><div className="authCard"><Activity/><h1>Preparing your LifeOS…</h1><p>Loading your private workspace.</p></div></div>
 if(isCloud&&!cloudUser)return <AuthScreen error={authError} onAuthed={(user,state)=>{setCloudUser(user);setS(valid(state)?state:{...seed,name:user.full_name});setAuthError('')}} />

 const income=useMemo(()=>s.transactions.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0),[s]),expenses=useMemo(()=>s.transactions.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0),[s])
 const taskRate=Math.round(s.tasks.filter(x=>x.done).length/Math.max(1,s.tasks.length)*100),habitRate=Math.round(s.habits.filter(x=>x.doneDates.includes(day())).length/Math.max(1,s.habits.length)*100),goalRate=Math.round(s.goals.reduce((a,x)=>a+x.progress,0)/Math.max(1,s.goals.length)),score=Math.round(taskRate*.4+habitRate*.35+goalRate*.25)
 const nav=[['Overview',LayoutDashboard],['Tasks',ListTodo],['Habits',Flame],['Goals',Target],['Finance',Wallet],['Notes',StickyNote],['Journal',BookOpen],['Focus',Timer],['Calendar',CalendarDays]] as const
 const toggleTask=(i:string)=>update(x=>({...x,tasks:x.tasks.map(t=>t.id===i?{...t,done:!t.done}:t)}))
 const toggleHabit=(i:string)=>update(x=>({...x,habits:x.habits.map(h=>h.id===i?{...h,doneDates:h.doneDates.includes(day())?h.doneDates.filter(d=>d!==day()):[...h.doneDates,day()]}:h)}))
 return <div className={dark?'app dark':'app'}>
  <aside className={menu?'sidebar open':'sidebar'}><div className="brand"><span className="brandIcon"><Activity/></span><div><b>LifeOS</b><small>PERSONAL OS</small></div><button className="mobileClose" onClick={()=>setMenu(false)}><X/></button></div><nav>{nav.map(([n,I])=><button key={n} className={page===n?'nav active':'nav'} onClick={()=>{setPage(n);setMenu(false)}}><I/>{n}</button>)}</nav><div className="sidebarBottom"><button className="nav" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}{dark?'Light mode':'Dark mode'}</button><button className="nav" onClick={()=>setProfileOpen(true)}><Settings/>Account & Settings</button><div className="profile" onClick={()=>setProfileOpen(true)} role="button" tabIndex={0}><div className="avatar">{s.name[0]?.toUpperCase()}</div><div><b>{s.name}</b><small>{cloudUser?.email||'Local workspace'}</small></div></div></div></aside>
  {menu&&<div className="mobileShade" onClick={()=>setMenu(false)}/>}<main className="main"><header className="topbar"><button className="mobileMenu iconBtn" onClick={()=>setMenu(true)}><ListTodo/></button><div><span className="eyebrow">{new Date().toDateString().toUpperCase()}</span><h1>{page==='Overview'?'Good evening, '+s.name+' 👋':page}</h1><p>Make today count. Small actions compound.</p></div><div className="topActions"><div className="searchBox"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search…"/></div><button className="iconBtn" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button className="primary" onClick={()=>setModal(true)}><Plus/>New task</button></div></header>
  {page==='Overview'&&<Overview s={s} score={score} taskRate={taskRate} habitRate={habitRate} income={income} expenses={expenses} toggleTask={toggleTask} toggleHabit={toggleHabit} setPage={setPage}/>}
  {page==='Tasks'&&<Tasks s={s} update={update} toggle={toggleTask}/>}
  {page==='Habits'&&<Habits s={s} update={update} toggle={toggleHabit}/>}
  {page==='Goals'&&<Goals s={s} update={update}/>}
  {page==='Finance'&&<Finance s={s} update={update} income={income} expenses={expenses}/>}
  {page==='Notes'&&<Notes s={s} update={update}/>}
  {page==='Journal'&&<Journal s={s} update={update}/>}
  {page==='Focus'&&<Focus s={s} update={update} flash={flash}/>}
  {page==='Calendar'&&<Calendar s={s} update={update}/>}
  {query&&<SearchResults q={query} s={s} setPage={setPage}/>}<footer><b>LifeOS</b> · {isCloud?<>Private cloud workspace {syncing?'· Syncing…':'· Synced'}</>:<>Local-first demo · Your data stays in this browser.</>}</footer></main>
  {modal&&<QuickModal onClose={()=>setModal(false)} update={update} flash={flash}/>}
  {profileOpen&&<ProfileModal user={cloudUser} onClose={()=>setProfileOpen(false)} onLogout={()=>{localStorage.removeItem(TOKEN_KEY);setCloudUser(null);setProfileOpen(false);setS({...seed,name:'New user',tasks:[],habits:[],goals:[],transactions:[],notes:[],journal:[],events:[],checkins:[]})}}/>}{toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}
 </div>
}

function AuthScreen(p:{error:string;onAuthed:(user:{id:string;full_name:string;email:string},state:Store)=>void}){
 const [mode,setMode]=useState<'login'|'register'>('register'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(p.error)
 const submit=async()=>{
   setError('');if(mode==='register'&&!name.trim())return setError('Please enter your name.')
   if(!email.includes('@'))return setError('Please enter a valid email.')
   if(password.length<8)return setError('Password must be at least 8 characters.')
   try{setBusy(true)
     const body=mode==='register'?{full_name:name.trim(),email,password}:{email,password}
     const data=await api<{access_token:string;user:{id:string;full_name:string;email:string}}>(`/api/v1/auth/${mode==='register'?'register':'login'}`,{method:'POST',body:JSON.stringify(body)})
     localStorage.setItem(TOKEN_KEY,data.access_token)
     const remote=await api<{data:Partial<Store>}>('/api/v1/state')
     const state=valid(remote.data)?remote.data as Store:{...seed,name:data.user.full_name,tasks:[],habits:[],goals:[],transactions:[],notes:[],journal:[],events:[],checkins:[]}
     await api('/api/v1/state',{method:'PUT',body:JSON.stringify({data:state})})
     p.onAuthed(data.user,state)
   }catch(e){setError(e instanceof Error?e.message:'Unable to continue')}finally{setBusy(false)}
 }
 return <div className="authShell"><div className="authCard">
   <div className="authBrand"><span className="brandIcon"><Activity/></span><span><b>LifeOS</b><small>PERSONAL OS</small></span></div>
   <span className="eyebrow">{mode==='register'?'YOUR PRIVATE WORKSPACE':'WELCOME BACK'}</span>
   <h1>{mode==='register'?'Build your life, one day at a time.':'Welcome back.'}</h1>
   <p className="authLead">Tasks, habits, goals, money, notes and reflections — in one calm place.</p>
   <div className="authTabs"><button className={mode==='login'?'active':''} onClick={()=>{setMode('login');setError('')}}>Sign in</button><button className={mode==='register'?'active':''} onClick={()=>{setMode('register');setError('')}}>Create account</button></div>
   {mode==='register'&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" autoComplete="name"/>}
   <input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" autoComplete="email"/>
   <input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (8+ characters)" autoComplete={mode==='login'?'current-password':'new-password'} onKeyDown={e=>e.key==='Enter'&&submit()}/>
   {error&&<div className="authError">{error}</div>}
   <button className="primary wide" disabled={busy} onClick={submit}>{busy?'Please wait…':mode==='register'?'Create my LifeOS':'Sign in to LifeOS'}</button>
   <small className="authPrivacy">Your account data belongs to your account. Use the same login on any supported device.</small>
 </div></div>
}

function ProfileModal(p:{user:{id:string;full_name:string;email:string}|null;onClose:()=>void;onLogout:()=>void}){return <div className="modalShade" onClick={p.onClose}><div className="modalCard profileModal" onClick={e=>e.stopPropagation()}><button className="modalClose" onClick={p.onClose}><X/></button><div className="profileHero"><div className="profileAvatar">{p.user?.full_name?.[0]?.toUpperCase()||'L'}</div><div><span className="eyebrow">YOUR ACCOUNT</span><h2>{p.user?.full_name||'Local workspace'}</h2><p>{p.user?.email||'This browser-only workspace is not connected to an account.'}</p></div></div><div className="profileRows"><div><span>Account</span><b>{p.user?'Cloud account':'Local workspace'}</b></div><div><span>Sync</span><b>{p.user?'Synced across devices':'Browser only'}</b></div><div><span>Privacy</span><b>Your data is scoped to your account</b></div></div>{p.user&&<button className="danger wide" onClick={p.onLogout}>Sign out</button>}<button className="secondary wide" onClick={p.onClose}>Close</button></div></div>}

function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="panel"><div className="panelHead"><div><span className="panelIcon">{icon}</span><h3>{title}</h3></div></div>{children}</section>}
function Overview(p:{s:Store;score:number;taskRate:number;habitRate:number;income:number;expenses:number;toggleTask:(i:string)=>void;toggleHabit:(i:string)=>void;setPage:(x:string)=>void}){return <div className="content"><section className="hero"><div className="heroMain"><div><span className="eyebrow">TODAY'S MOMENTUM</span><h2>Build the life you want,<br/><span>one day at a time.</span></h2><p>Your personal dashboard for focus, habits, goals and money.</p></div><div className="scoreRing"><strong>{p.score}</strong><span>/100</span><small>Momentum</small></div></div><div className="heroStats"><div><Flame/><b>{streak(p.s.checkins)}</b><span>day streak</span></div><div><CheckCircle2/><b>{p.taskRate}%</b><span>tasks complete</span></div><div><Target/><b>{p.habitRate}%</b><span>habits today</span></div><button onClick={()=>p.setPage('Journal')}><Sparkles/> Check in</button></div></section><section className="grid3"><Panel title="Today's tasks" icon={<ListTodo/>}><div className="list">{p.s.tasks.slice(0,4).map(t=><button className="row" key={t.id} onClick={()=>p.toggleTask(t.id)}><span className={t.done?'check done':'check'}>{t.done&&<Check/>}</span><span className={t.done?'strike':''}>{t.title}</span><em className={'p '+t.priority.toLowerCase()}>{t.priority}</em></button>)}</div></Panel><Panel title="Habit pulse" icon={<Flame/>}><div className="list">{p.s.habits.map(h=><button className="row" key={h.id} onClick={()=>p.toggleHabit(h.id)}><span className={h.doneDates.includes(day())?'check done':'check'}>{h.doneDates.includes(day())&&<Check/>}</span><span>{h.name}</span><em className="streak"><Flame size={13}/>{streak(h.doneDates)}</em></button>)}</div></Panel><Panel title="Money snapshot" icon={<Wallet/>}><div className="moneyHero"><small>NET SAVINGS</small><strong>{money(p.income-p.expenses)}</strong><span><TrendingUp size={14}/> this month</span></div><div className="moneyLine"><span>Income</span><b>{money(p.income)}</b></div><div className="moneyLine"><span>Expenses</span><b>{money(p.expenses)}</b></div></Panel></section><section className="grid2"><Panel title="Goals in motion" icon={<Target/>}><div className="goalList">{p.s.goals.map(g=><div className="goal" key={g.id}><div className="goalTop"><span>{g.title}</span><b>{g.progress}%</b></div><div className="bar"><i style={{width:g.progress+'%'}}/></div><small>{g.deadline}</small></div>)}</div></Panel><Panel title="LifeOS at a glance" icon={<BarChart3/>}><div className="metricGrid"><div><span>Goals average</span><b>{Math.round(p.s.goals.reduce((a,g)=>a+g.progress,0)/Math.max(1,p.s.goals.length))}%</b></div><div><span>Focus sessions</span><b>{p.s.journal.length}</b></div><div><span>Notes</span><b>{p.s.notes.length}</b></div><div><span>Events</span><b>{p.s.events.length}</b></div></div></Panel></section></div>}

function Tasks(p:{s:Store;update:(f:(s:Store)=>Store)=>void;toggle:(i:string)=>void}){const [v,setV]=useState('');return <div className="content page"><Panel title="Task inbox" icon={<ListTodo/>}><div className="quick"><input value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&v){p.update(s=>({...s,tasks:[...s.tasks,{id:id(),title:v,done:false,priority:'Medium'}]}));setV('')}}} placeholder="Add a task…"/><button className="primary" onClick={()=>{if(v){p.update(s=>({...s,tasks:[...s.tasks,{id:id(),title:v,done:false,priority:'Medium'}]}));setV('')}}}><Plus/>Add</button></div>{p.s.tasks.map(t=><div className="taskItem" key={t.id}><button className={t.done?'check done':'check'} onClick={()=>p.toggle(t.id)}>{t.done&&<Check/>}</button><div className="grow"><b className={t.done?'strike':''}>{t.title}</b><small>{t.priority} priority</small></div><button className="delete" onClick={()=>p.update(s=>({...s,tasks:s.tasks.filter(x=>x.id!==t.id)}))}><Trash2/></button></div>)}</Panel></div>}
function Habits(p:{s:Store;update:(f:(s:Store)=>Store)=>void;toggle:(i:string)=>void}){const [v,setV]=useState('');return <div className="content page"><Panel title="Habit tracker" icon={<Flame/>}><div className="quick"><input value={v} onChange={e=>setV(e.target.value)} placeholder="Create a habit…"/><button className="primary" onClick={()=>{if(v){p.update(s=>({...s,habits:[...s.habits,{id:id(),name:v,doneDates:[]}]}));setV('')}}}><Plus/>Add</button></div><div className="habitCards">{p.s.habits.map(h=><div className="habitCard" key={h.id}><button className={h.doneDates.includes(day())?'habitCheck active':'habitCheck'} onClick={()=>p.toggle(h.id)}>{h.doneDates.includes(day())?<Check/>:<Circle/>}</button><div className="grow"><b>{h.name}</b><small>{h.doneDates.includes(day())?'Completed today':'Tap to complete today'}</small></div><strong><Flame size={15}/>{streak(h.doneDates)}<small>day streak</small></strong><button className="delete" onClick={()=>p.update(s=>({...s,habits:s.habits.filter(x=>x.id!==h.id)}))}><Trash2/></button></div>)}</div></Panel></div>}
function Goals(p:{s:Store;update:(f:(s:Store)=>Store)=>void}){return <div className="content page"><Panel title="Goals" icon={<Target/>}><div className="goalCards">{p.s.goals.map(g=><div className="goalCard" key={g.id}><div className="goalTop"><b>{g.title}</b><button className="delete" onClick={()=>p.update(s=>({...s,goals:s.goals.filter(x=>x.id!==g.id)}))}><Trash2/></button></div><div className="goalBig"><strong>{g.progress}%</strong><span>complete</span></div><input className="range" type="range" min="0" max="100" value={g.progress} onChange={e=>p.update(s=>({...s,goals:s.goals.map(x=>x.id===g.id?{...x,progress:+e.target.value}:x)}))}/><small>Target · {g.deadline}</small></div>)}</div></Panel></div>}
function Finance(p:{s:Store;update:(f:(s:Store)=>Store)=>void;income:number;expenses:number}){const [label,setLabel]=useState(''),[amt,setAmt]=useState(''),[type,setType]=useState<'income'|'expense'>('expense');return <div className="content page"><section className="financeCards"><div><small>INCOME</small><strong>{money(p.income)}</strong></div><div><small>EXPENSES</small><strong>{money(p.expenses)}</strong></div><div><small>SAVINGS</small><strong>{money(p.income-p.expenses)}</strong></div></section><Panel title="Add transaction" icon={<Wallet/>}><div className="financeForm"><input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Description"/><input type="number" value={amt} onChange={e=>setAmt(e.target.value)} placeholder="Amount"/><select value={type} onChange={e=>setType(e.target.value as 'income'|'expense')}><option value="expense">Expense</option><option value="income">Income</option></select><button className="primary" onClick={()=>{if(label&&+amt){p.update(s=>({...s,transactions:[...s.transactions,{id:id(),label,amount:+amt,type,category:'General'}]}));setLabel('');setAmt('')}}}><Plus/>Add</button></div></Panel><Panel title="Transactions" icon={<Wallet/>}>{p.s.transactions.slice().reverse().map(x=><div className="taskItem" key={x.id}><span className={x.type==='income'?'txIcon income':'txIcon expense'}>{x.type==='income'?'+':'−'}</span><div className="grow"><b>{x.label}</b><small>{x.category}</small></div><strong className={x.type}>{x.type==='income'?'+':'−'} {money(x.amount)}</strong><button className="delete" onClick={()=>p.update(s=>({...s,transactions:s.transactions.filter(t=>t.id!==x.id)}))}><Trash2/></button></div>)}</Panel></div>}
function Notes(p:{s:Store;update:(f:(s:Store)=>Store)=>void}){const [t,setT]=useState(''),[c,setC]=useState('');return <div className="content page"><Panel title="Notes" icon={<StickyNote/>}><div className="noteEditor"><input value={t} onChange={e=>setT(e.target.value)} placeholder="Title"/><textarea value={c} onChange={e=>setC(e.target.value)} placeholder="Write anything…"/><button className="primary" onClick={()=>{if(t||c){p.update(s=>({...s,notes:[...s.notes,{id:id(),title:t||'Untitled',content:c}]}));setT('');setC('')}}}><Save/>Save note</button></div><div className="noteGrid">{p.s.notes.map(n=><article className="noteCard" key={n.id}><button className="delete" onClick={()=>p.update(s=>({...s,notes:s.notes.filter(x=>x.id!==n.id)}))}><Trash2/></button><h3>{n.title}</h3><p>{n.content}</p></article>)}</div></Panel></div>}
function Journal(p:{s:Store;update:(f:(s:Store)=>Store)=>void}){const [v,setV]=useState(''),[m,setM]=useState('Focused');return <div className="content page"><Panel title="Daily journal" icon={<BookOpen/>}><div className="moods">{['Great','Focused','Calm','Okay','Tired'].map(x=><button className={m===x?'mood active':'mood'} key={x} onClick={()=>setM(x)}>{x}</button>)}</div><textarea className="journalText" value={v} onChange={e=>setV(e.target.value)} placeholder="How did today go? What did you learn?"/><button className="primary" onClick={()=>{if(v){p.update(s=>({...s,journal:[...s.journal,{id:id(),date:day(),mood:m,text:v}]}));setV('')}}}><Save/>Save reflection</button>{p.s.journal.slice().reverse().map(j=><div className="journalItem" key={j.id}><b>{j.date} · {j.mood}</b><p>{j.text}</p><button className="delete" onClick={()=>p.update(s=>({...s,journal:s.journal.filter(x=>x.id!==j.id)}))}><Trash2/></button></div>)}</Panel></div>}
function Focus(p:{s:Store;update:(f:(s:Store)=>Store)=>void;flash:(x:string)=>void}){const [sec,setSec]=useState(1500),[run,setRun]=useState(false);useEffect(()=>{if(!run)return;const t=setInterval(()=>setSec(x=>{if(x<=1){clearInterval(t);setRun(false);p.update(s=>({...s,checkins:s.checkins.includes(day())?s.checkins:[...s.checkins,day()]}));p.flash('Focus session complete!');return 1500}return x-1}),1000);return()=>clearInterval(t)},[run]);return <div className="content page"><div className="focusLayout"><Panel title="Focus timer" icon={<Timer/>}><div className="timer"><span>{String(Math.floor(sec/60)).padStart(2,'0')}:{String(sec%60).padStart(2,'0')}</span><div><button className="primary" onClick={()=>setRun(!run)}>{run?'Pause':'Start focus'}</button><button className="secondary" onClick={()=>{setRun(false);setSec(1500)}}><RotateCcw/>Reset</button></div></div></Panel><Panel title="Focus guide" icon={<Clock3/>}><div className="metricGrid"><div><span>Method</span><b>25 / 5</b></div><div><span>Today</span><b>{p.s.checkins.length}</b></div></div><p className="muted">Put one task in front of you, remove distractions, and finish the block.</p></Panel></div></div>}
function Calendar(p:{s:Store;update:(f:(s:Store)=>Store)=>void}){const [t,setT]=useState(''),[d,setD]=useState(day()),[tm,setTm]=useState('20:00');return <div className="content page"><Panel title="Calendar" icon={<CalendarDays/>}><div className="calendarForm"><input value={t} onChange={e=>setT(e.target.value)} placeholder="Event title"/><input type="date" value={d} onChange={e=>setD(e.target.value)}/><input type="time" value={tm} onChange={e=>setTm(e.target.value)}/><button className="primary" onClick={()=>{if(t){p.update(s=>({...s,events:[...s.events,{id:id(),title:t,date:d,time:tm}]}));setT('')}}}><Plus/>Add</button></div>{p.s.events.map(e=><div className="eventItem" key={e.id}><div className="eventDate"><b>{e.date.slice(8)}</b><small>{e.date.slice(5,7)}</small></div><div className="grow"><b>{e.title}</b><small>{e.time}</small></div><button className="delete" onClick={()=>p.update(s=>({...s,events:s.events.filter(x=>x.id!==e.id)}))}><Trash2/></button></div>)}</Panel></div>}
function SearchResults(p:{q:string;s:Store;setPage:(x:string)=>void}){const q=p.q.toLowerCase();const r=[...p.s.tasks.filter(x=>x.title.toLowerCase().includes(q)).map(x=>['Tasks',x.title]),...p.s.habits.filter(x=>x.name.toLowerCase().includes(q)).map(x=>['Habits',x.name]),...p.s.goals.filter(x=>x.title.toLowerCase().includes(q)).map(x=>['Goals',x.title]),...p.s.notes.filter(x=>x.title.toLowerCase().includes(q)).map(x=>['Notes',x.title])];if(!r.length)return null;return <div className="searchResults">{r.slice(0,7).map((x,i)=><button key={i} onClick={()=>p.setPage(x[0])}><span>{x[0]}</span><b>{x[1]}</b></button>)}</div>}
function QuickModal(p:{onClose:()=>void;update:(f:(s:Store)=>Store)=>void;flash:(x:string)=>void}){const [v,setV]=useState('');return <div className="modalBack" onClick={p.onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modalHead"><div><span className="eyebrow">QUICK CAPTURE</span><h2>Add a task</h2></div><button className="iconBtn" onClick={p.onClose}><X/></button></div><input autoFocus value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&v){p.update(s=>({...s,tasks:[...s.tasks,{id:id(),title:v,done:false,priority:'Medium'}]}));p.flash('Task added');p.onClose()}}} placeholder="What needs to get done?"/><button className="primary wide" onClick={()=>{if(v){p.update(s=>({...s,tasks:[...s.tasks,{id:id(),title:v,done:false,priority:'Medium'}]}));p.flash('Task added');p.onClose()}}}><Plus/>Add task</button></div></div>}
